# Generated by Django 6.0.5 on 2026-05-05 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage off'), ('bogo', 'Buy one get one (2-for-1)'), ('fixed_price', 'Fixed price deal'), ('promo_code', 'Promo code / voucher')], max_length=20)),
                ('percentage', models.PositiveSmallIntegerField(blank=True, help_text='Used when type is Percentage. e.g. 25 for 25% off.', null=True)),
                ('fixed_price_aed', models.DecimalField(blank=True, decimal_places=2, help_text='Used when type is Fixed price. Price in AED.', max_digits=8, null=True)),
                ('promo_code', models.CharField(blank=True, help_text='Used when type is Promo code. Code the customer presents/enters.', max_length=64)),
                ('description', models.TextField()),
                ('terms', models.TextField(blank=True, help_text='Fine print, exclusions, hours, etc.')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, help_text='Leave blank for ongoing offers.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='places.place')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
                'indexes': [models.Index(fields=['discount_type'], name='discounts_d_discoun_f47d7f_idx'), models.Index(fields=['is_active', 'is_featured'], name='discounts_d_is_acti_3187c2_idx'), models.Index(fields=['valid_until'], name='discounts_d_valid_u_8bdc37_idx')],
            },
        ),
    ]
