# Generated by Django 6.0.5 on 2026-05-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_discount_is_members_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='source_program',
            field=models.CharField(blank=True, choices=[('in_house', 'Loyalty program'), ('fazaa', 'Fazaa'), ('esaad', 'Esaad'), ('entertainer', 'Entertainer')], default='', help_text='Which program/card offers this discount. Leave blank if none.', max_length=20),
        ),
    ]
