# Generated by Django 6.0.5 on 2026-05-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0005_add_caribou_coffee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('short_description', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('official_url', models.URLField()),
                ('cost_summary', models.CharField(blank=True, help_text="e.g. 'Free', 'AED 275/year'", max_length=80)),
                ('eligibility', models.CharField(blank=True, help_text="e.g. 'UAE residents', 'Emirates Group employees'", max_length=160)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=100, help_text='Lower = higher up in the directory.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='discount',
            name='source_program',
            field=models.CharField(blank=True, choices=[('in_house', 'Loyalty program'), ('fazaa', 'Fazaa'), ('esaad', 'Esaad'), ('entertainer', 'Entertainer'), ('zomato', 'Zomato Pro / Gold'), ('repeat', 'Repeat'), ('elite_club', 'Elite Club'), ('supper_club', 'Supper Club ME'), ('emirates_platinum', 'Emirates Platinum'), ('shukran', 'Shukran'), ('share_rewards', 'SHARE Rewards'), ('emirates_skywards', 'Emirates Skywards')], default='', help_text='Which program/card offers this discount. Leave blank if none.', max_length=20),
        ),
    ]
