# Generated by Django 6.0.5 on 2026-05-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0009_replace_supper_club_with_sitemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='external_url',
            field=models.URLField(blank=True, help_text="Source-of-truth link, e.g. the Fazaa/Supper Club/Entertainer offer page or the venue's loyalty signup page."),
        ),
    ]
