# Generated by Django 6.0.5 on 2026-05-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0010_add_discount_external_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='external_url',
            field=models.URLField(blank=True, help_text="Source-of-truth link, e.g. the Fazaa/Supper Club/Entertainer offer page or the venue's loyalty signup page.", max_length=500),
        ),
    ]
