# Generated by Django 6.0.5 on 2026-05-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0018_add_eliteclub_venues'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='expected_savings',
            field=models.CharField(blank=True, help_text='One-line summary of typical savings, shown under the tier table.', max_length=240),
        ),
        migrations.AddField(
            model_name='program',
            name='tiers',
            field=models.JSONField(blank=True, default=list, help_text='List of {name, threshold, benefit} dicts shown as a table on the program detail page.'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='source_program',
            field=models.CharField(blank=True, choices=[('in_house', 'Loyalty program'), ('fazaa', 'Fazaa'), ('esaad', 'Esaad'), ('entertainer', 'Entertainer'), ('zomato', 'Zomato Pro / Gold'), ('repeat', 'Repeat'), ('elite_club', 'Elite Club'), ('supper_club', 'Supper Club ME'), ('emirates_platinum', 'Emirates Platinum'), ('shukran', 'Shukran'), ('share_rewards', 'SHARE Rewards'), ('emirates_skywards', 'Emirates Skywards'), ('atlantis_circle', 'Atlantis Circle'), ('u_by_emaar', 'U By Emaar'), ('al_futtaim_blue', 'Blue (Al-Futtaim)')], default='', help_text='Which program/card offers this discount. Leave blank if none.', max_length=20),
        ),
    ]
