# Generated by Django 6.0.5 on 2026-05-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0026_atlantis_circle_venues'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='is_gem',
            field=models.BooleanField(default=False, help_text='Curator pick highlighted with a diamond icon to all users.'),
        ),
    ]
