# Generated by Django 6.0.5 on 2026-05-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0029_seed_playbook_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage off'), ('bogo', 'Buy one get one (2-for-1)'), ('fixed_price', 'Fixed price deal'), ('promo_code', 'Promo code / voucher'), ('referral', 'Refer a friend'), ('other', 'Special offer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='discount',
            name='source_program',
            field=models.CharField(blank=True, choices=[('in_house', 'Loyalty program'), ('fazaa', 'Fazaa'), ('esaad', 'Esaad'), ('entertainer', 'Entertainer'), ('zomato', 'Zomato Pro / Gold'), ('repeat', 'Repeat'), ('playbook', 'Playbook'), ('elite_club', 'Elite Club'), ('supper_club', 'Supper Club ME'), ('emirates_platinum', 'Emirates Platinum'), ('shukran', 'Shukran'), ('share_rewards', 'SHARE Rewards'), ('emirates_skywards', 'Emirates Skywards'), ('atlantis_circle', 'Atlantis Circle'), ('u_by_emaar', 'U By Emaar'), ('al_futtaim_blue', 'Blue (Al-Futtaim)'), ('referral', 'Refer & Earn')], default='', help_text='Which program/card offers this discount. Leave blank if none.', max_length=20),
        ),
    ]
