"""Seed the Refer & Earn program directory: one Program row + ~25 Places
+ Discounts for curated UAE referral programs (Careem, Talabat, Mashreq NEO,
The Little Gym, etc.).

Generated by scripts/gen_referrals_migration.py from data/referrals_enriched.json.
Re-running the generator overwrites this file. The migration itself is
idempotent (upsert on slug)."""
from django.db import migrations


PROGRAM = {
    'slug': 'referral',
    'name': 'Refer & Earn',
    'short_description': 'Brand referral programs for UAE services — share your code, both you and your friend earn credit, cashback, or free months.',
    'description': "A curated directory of public Refer-a-Friend programs from UAE apps and services. Each entry links to the brand's official referral page where you can sign in, get your unique code, and share it. Most programs reward both sides of the referral — credit, cashback, free data, or a complimentary month — when the friend completes their first qualifying purchase or signup.\n\nWe only list programs whose terms are publicly published. Codes themselves are per-user and rotate, so they're not stored here — tap through to the brand's page to grab yours.",
    'official_url': '',
    'cost_summary': 'Free',
    'eligibility': 'Anyone with an account on the underlying brand',
    'sort_order': 80,
    'tiers': [],
    'expected_savings': 'Typical bonuses range from AED 20–100 per successful referral, or one free month of membership for fitness/lifestyle programs. Active referrers can stack AED 200–500 in credits per year across delivery, fintech, and telco programs.',
}


PLACES = [
    {
        'slug': 'careem-pay',
        'name': 'Careem Pay',
        'category': 'service',
        'area': '',
        'website': 'https://www.careem.com',
    },
    {
        'slug': 'talabat',
        'name': 'Talabat',
        'category': 'service',
        'area': '',
        'website': 'https://www.talabat.com',
    },
    {
        'slug': 'noon',
        'name': 'Noon',
        'category': 'service',
        'area': '',
        'website': 'https://www.noon.com',
    },
    {
        'slug': 'deliveroo',
        'name': 'Deliveroo',
        'category': 'service',
        'area': '',
        'website': 'https://deliveroo.ae',
    },
    {
        'slug': 'kibsons',
        'name': 'Kibsons',
        'category': 'service',
        'area': '',
        'website': 'https://www.kibsons.com',
    },
    {
        'slug': 'instashop',
        'name': 'InstaShop',
        'category': 'service',
        'area': '',
        'website': 'https://www.instashop.com',
    },
    {
        'slug': 'carrefour-uae',
        'name': 'Carrefour UAE',
        'category': 'service',
        'area': '',
        'website': 'https://www.carrefouruae.com',
    },
    {
        'slug': 'amazon-ae',
        'name': 'Amazon.ae',
        'category': 'service',
        'area': '',
        'website': 'https://www.amazon.ae',
    },
    {
        'slug': 'mashreq-neo',
        'name': 'Mashreq NEO',
        'category': 'service',
        'area': '',
        'website': 'https://www.mashreq.com',
    },
    {
        'slug': 'adcb-hayyak',
        'name': 'ADCB Hayyak',
        'category': 'service',
        'area': '',
        'website': 'https://www.adcb.com',
    },
    {
        'slug': 'liv-bank',
        'name': 'Liv. Digital Bank',
        'category': 'service',
        'area': '',
        'website': 'https://www.liv.me',
    },
    {
        'slug': 'etisalat-by-e-and',
        'name': 'Etisalat by e&',
        'category': 'service',
        'area': '',
        'website': 'https://www.etisalat.ae',
    },
    {
        'slug': 'du-uae',
        'name': 'du',
        'category': 'service',
        'area': '',
        'website': 'https://www.du.ae',
    },
    {
        'slug': 'rain-payments',
        'name': 'Rain',
        'category': 'service',
        'area': '',
        'website': 'https://www.rain.com',
    },
    {
        'slug': 'yap-uae',
        'name': 'YAP',
        'category': 'service',
        'area': '',
        'website': 'https://www.yap.com',
    },
    {
        'slug': 'rehlat',
        'name': 'Rehlat',
        'category': 'service',
        'area': '',
        'website': 'https://www.rehlat.ae',
    },
    {
        'slug': 'cobone',
        'name': 'Cobone',
        'category': 'service',
        'area': '',
        'website': 'https://www.cobone.com',
    },
    {
        'slug': 'fitness-first-uae',
        'name': 'Fitness First Middle East',
        'category': 'attraction',
        'area': 'Multiple branches',
        'website': 'https://www.fitnessfirstme.com',
    },
    {
        'slug': 'warehouse-gym',
        'name': 'The Warehouse Gym',
        'category': 'attraction',
        'area': 'Multiple branches',
        'website': 'https://thewarehousegym.com',
    },
    {
        'slug': 'the-little-gym-dubai',
        'name': 'The Little Gym Dubai',
        'category': 'attraction',
        'area': 'Multiple branches',
        'website': 'https://thelittlegymdubai.com',
    },
    {
        'slug': 'kidzania-dubai',
        'name': 'KidZania Dubai',
        'category': 'attraction',
        'area': 'Dubai Mall',
        'website': 'https://kidzania.ae',
    },
    {
        'slug': 'privilee',
        'name': 'Privilee',
        'category': 'service',
        'area': '',
        'website': 'https://privilee.ae',
    },
    {
        'slug': 'the-select-app',
        'name': 'The Select App',
        'category': 'service',
        'area': '',
        'website': 'https://www.theselectapp.com',
    },
    {
        'slug': 'washmen',
        'name': 'Washmen',
        'category': 'service',
        'area': '',
        'website': 'https://washmen.com',
    },
    {
        'slug': 'justlife',
        'name': 'Justlife',
        'category': 'service',
        'area': '',
        'website': 'https://justlife.com',
    },
]


DISCOUNTS = [
    {
        'place_slug': 'careem-pay',
        'discount_slug': 'careem-pay-referral',
        'title': 'Refer & Earn — Careem Pay',
        'description': 'Refer a friend to Careem Pay — earn AED 40 in your wallet for every friend who sends at least AED 1,000 using your link. Up to AED 2,000 in total (50 successful referrals).',
        'external_url': 'https://www.careem.com/en-AE/pay/referral/',
    },
    {
        'place_slug': 'talabat',
        'discount_slug': 'talabat-referral',
        'title': 'Refer & Earn — Talabat',
        'description': 'Invite a friend — both of you get AED 30 off your next order on Talabat.',
        'external_url': 'https://www.talabat.com/uae/refer-a-friend',
    },
    {
        'place_slug': 'noon',
        'discount_slug': 'noon-referral',
        'title': 'Refer & Earn — Noon',
        'description': 'Refer friends to noon — earn store credit when they place a qualifying first order.',
        'external_url': 'https://www.noon.com/uae-en/sell/referral',
    },
    {
        'place_slug': 'deliveroo',
        'discount_slug': 'deliveroo-referral',
        'title': 'Refer & Earn — Deliveroo',
        'description': 'Share your Deliveroo code — your friend gets AED 25 off their first order, you earn AED 25 in credit.',
        'external_url': 'https://deliveroo.ae/refer-a-friend',
    },
    {
        'place_slug': 'kibsons',
        'discount_slug': 'kibsons-referral',
        'title': 'Refer & Earn — Kibsons',
        'description': 'Refer a friend to Kibsons — both get AED 50 in credit when they place their first order.',
        'external_url': 'https://www.kibsons.com/refer-a-friend',
    },
    {
        'place_slug': 'instashop',
        'discount_slug': 'instashop-referral',
        'title': 'Refer & Earn — InstaShop',
        'description': 'Invite a friend to InstaShop — both of you get AED 25 off your next grocery order.',
        'external_url': 'https://www.instashop.com/en-ae/referral',
    },
    {
        'place_slug': 'carrefour-uae',
        'discount_slug': 'carrefour-uae-referral',
        'title': 'Refer & Earn — Carrefour UAE',
        'description': 'Refer a friend to Carrefour — both get AED 50 off when they spend AED 100 on their first order.',
        'external_url': 'https://www.carrefouruae.com/mafuae/en/c/refer-and-earn',
    },
    {
        'place_slug': 'amazon-ae',
        'discount_slug': 'amazon-ae-referral',
        'title': 'Refer & Earn — Amazon.ae',
        'description': 'Amazon.ae runs limited-time Refer-a-Friend promotions — invite friends from Your Account when active.',
        'external_url': 'https://www.amazon.ae/gp/help/customer/display.html?nodeId=GLLR3DP9KNAYTZX9',
    },
    {
        'place_slug': 'mashreq-neo',
        'discount_slug': 'mashreq-neo-referral',
        'title': 'Refer & Earn — Mashreq NEO',
        'description': 'Refer up to 5 friends to Mashreq NEO in 90 days — earn AED 100–200 per successful referral.',
        'external_url': 'https://www.mashreq.com/uae/neo/refer-and-earn/refer-accounts/',
    },
    {
        'place_slug': 'adcb-hayyak',
        'discount_slug': 'adcb-hayyak-referral',
        'title': 'Refer & Earn — ADCB Hayyak',
        'description': 'Refer a friend to ADCB — when they open an eligible account, you both get a cash reward.',
        'external_url': 'https://www.adcb.com/en/personal/promotions/refer-a-friend',
    },
    {
        'place_slug': 'liv-bank',
        'discount_slug': 'liv-bank-referral',
        'title': 'Refer & Earn — Liv. Digital Bank',
        'description': 'Refer a friend to Liv. — earn cashback when they open and fund their account.',
        'external_url': 'https://www.liv.me/en/refer-and-earn',
    },
    {
        'place_slug': 'etisalat-by-e-and',
        'discount_slug': 'etisalat-by-e-and-referral',
        'title': 'Refer & Earn — Etisalat by e&',
        'description': 'Invite a friend to e& — get 500MB of free mobile data per successful invite.',
        'external_url': 'https://www.etisalat.ae/en/c/invite-a-friend.html',
    },
    {
        'place_slug': 'du-uae',
        'discount_slug': 'du-uae-referral',
        'title': 'Refer & Earn — du',
        'description': 'Refer a friend to du — both of you get bonus mobile data when they activate a new line.',
        'external_url': 'https://www.du.ae/personal/mobile/refer-a-friend',
    },
    {
        'place_slug': 'rain-payments',
        'discount_slug': 'rain-payments-referral',
        'title': 'Refer & Earn — Rain',
        'description': 'Refer a friend to Rain — both of you earn USD 5 in crypto when they pass identity verification and trade.',
        'external_url': 'https://www.rain.com/en/referrals',
    },
    {
        'place_slug': 'yap-uae',
        'discount_slug': 'yap-uae-referral',
        'title': 'Refer & Earn — YAP',
        'description': 'Refer a friend to YAP — both of you get AED 50 in your YAP wallet when they top up for the first time.',
        'external_url': 'https://www.yap.com/en-ae/refer-a-friend',
    },
    {
        'place_slug': 'rehlat',
        'discount_slug': 'rehlat-referral',
        'title': 'Refer & Earn — Rehlat',
        'description': 'Refer friends to Rehlat — earn travel credit when they book their first flight or hotel.',
        'external_url': 'https://www.rehlat.ae/en/referandearn',
    },
    {
        'place_slug': 'cobone',
        'discount_slug': 'cobone-referral',
        'title': 'Refer & Earn — Cobone',
        'description': 'Refer a friend to Cobone — both of you get AED 25 in deal credit when they make their first purchase.',
        'external_url': 'https://www.cobone.com/en/refer-a-friend',
    },
    {
        'place_slug': 'fitness-first-uae',
        'discount_slug': 'fitness-first-uae-referral',
        'title': 'Refer & Earn — Fitness First Middle East',
        'description': 'Refer a friend to Fitness First — when they sign up for a membership, you receive a complimentary month.',
        'external_url': 'https://www.fitnessfirstme.com/refer-a-friend/',
    },
    {
        'place_slug': 'warehouse-gym',
        'discount_slug': 'warehouse-gym-referral',
        'title': 'Refer & Earn — The Warehouse Gym',
        'description': 'Refer a friend to The Warehouse Gym — earn a free month added to your membership when they join.',
        'external_url': 'https://thewarehousegym.com/refer-a-friend/',
    },
    {
        'place_slug': 'the-little-gym-dubai',
        'discount_slug': 'the-little-gym-dubai-referral',
        'title': 'Refer & Earn — The Little Gym Dubai',
        'description': 'Refer a friend to The Little Gym — receive a free class when their child enrolls in a term.',
        'external_url': 'https://thelittlegymdubai.com/refer-a-friend/',
    },
    {
        'place_slug': 'kidzania-dubai',
        'discount_slug': 'kidzania-dubai-referral',
        'title': 'Refer & Earn — KidZania Dubai',
        'description': 'Refer a friend to KidZania Dubai — both of you earn KidZos credit when they purchase an annual pass.',
        'external_url': 'https://kidzania.ae/en/membership/refer-a-friend',
    },
    {
        'place_slug': 'privilee',
        'discount_slug': 'privilee-referral',
        'title': 'Refer & Earn — Privilee',
        'description': 'Refer a friend to Privilee — both of you get one bonus month added to your membership when they join.',
        'external_url': 'https://privilee.ae/refer-a-friend',
    },
    {
        'place_slug': 'the-select-app',
        'discount_slug': 'the-select-app-referral',
        'title': 'Refer & Earn — The Select App',
        'description': 'Share your Select code — when a friend subscribes, both of you receive bonus offers credit.',
        'external_url': 'https://www.theselectapp.com/refer-a-friend',
    },
    {
        'place_slug': 'washmen',
        'discount_slug': 'washmen-referral',
        'title': 'Refer & Earn — Washmen',
        'description': 'Refer a friend to Washmen — both of you get AED 50 off your next laundry order.',
        'external_url': 'https://washmen.com/uae/refer-a-friend',
    },
    {
        'place_slug': 'justlife',
        'discount_slug': 'justlife-referral',
        'title': 'Refer & Earn — Justlife',
        'description': 'Refer a friend to Justlife — both of you get AED 50 off your next home-services booking.',
        'external_url': 'https://justlife.com/en-ae/refer-a-friend',
    },
]


def seed(apps, schema_editor):
    Program = apps.get_model("discounts", "Program")
    Place = apps.get_model("places", "Place")
    Discount = apps.get_model("discounts", "Discount")

    Program.objects.update_or_create(
        slug=PROGRAM["slug"],
        defaults={k: v for k, v in PROGRAM.items() if k != "slug"},
    )

    place_by_slug = {}
    for spec in PLACES:
        place, _ = Place.objects.update_or_create(
            slug=spec["slug"],
            defaults={
                "name": spec["name"],
                "category": spec["category"],
                "area": spec["area"],
                "website": spec.get("website", ""),
                "is_published": True,
            },
        )
        place_by_slug[spec["slug"]] = place

    for d in DISCOUNTS:
        place = place_by_slug.get(d["place_slug"])
        if place is None:
            continue
        Discount.objects.update_or_create(
            slug=d["discount_slug"],
            defaults={
                "place": place,
                "title": d["title"][:200],
                "discount_type": "referral",
                "source_program": "referral",
                "description": d["description"],
                "external_url": d["external_url"],
                "is_active": True,
                "is_featured": False,
            },
        )


def reverse(apps, schema_editor):
    Program = apps.get_model("discounts", "Program")
    Place = apps.get_model("places", "Place")
    Discount = apps.get_model("discounts", "Discount")
    Discount.objects.filter(slug__in=[d["discount_slug"] for d in DISCOUNTS]).delete()
    Place.objects.filter(slug__in=[p["slug"] for p in PLACES]).delete()
    Program.objects.filter(slug=PROGRAM["slug"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0030_alter_discount_discount_type_and_more"),
        ("places", "0006_alter_place_area_alter_place_category"),
    ]

    operations = [
        migrations.RunPython(seed, reverse),
    ]
