"""Seed the Refer & Earn program directory: one Program row + ~4 Places
+ Discounts for curated UAE referral programs (Careem, Talabat, Mashreq NEO,
The Little Gym, etc.).

Generated by scripts/gen_referrals_migration.py from data/referrals_enriched.json.
Re-running the generator overwrites this file. The migration itself is
idempotent (upsert on slug)."""
from django.db import migrations


PROGRAM = {
    'slug': 'referral',
    'name': 'Refer & Earn',
    'short_description': 'Brand referral programs for UAE services — share your code, both you and your friend earn credit, cashback, or free months.',
    'description': "A curated directory of public Refer-a-Friend programs from UAE apps and services. Each entry links to the brand's official referral page where you can sign in, get your unique code, and share it. Most programs reward both sides of the referral — credit, cashback, free data, or a complimentary month — when the friend completes their first qualifying purchase or signup.\n\nWe only list programs whose terms are publicly published. Codes themselves are per-user and rotate, so they're not stored here — tap through to the brand's page to grab yours.",
    'official_url': '',
    'cost_summary': 'Free',
    'eligibility': 'Anyone with an account on the underlying brand',
    'sort_order': 80,
    'tiers': [],
    'expected_savings': 'Typical bonuses range from AED 20–100 per successful referral, or one free month of membership for fitness/lifestyle programs. Active referrers can stack AED 200–500 in credits per year across delivery, fintech, and telco programs.',
}


PLACES = [
    {
        'slug': 'mashreq-neo',
        'name': 'Mashreq NEO',
        'category': 'service',
        'area': '',
        'website': 'https://www.mashreq.com',
    },
    {
        'slug': 'adcb-hayyak',
        'name': 'ADCB Hayyak',
        'category': 'service',
        'area': '',
        'website': 'https://www.adcb.com',
    },
    {
        'slug': 'etisalat-by-e-and',
        'name': 'Etisalat by e&',
        'category': 'service',
        'area': '',
        'website': 'https://www.etisalat.ae',
    },
    {
        'slug': 'du-pay',
        'name': 'du Pay',
        'category': 'service',
        'area': '',
        'website': 'https://dupay.ae',
    },
]


DISCOUNTS = [
    {
        'place_slug': 'mashreq-neo',
        'discount_slug': 'mashreq-neo-referral',
        'title': 'Refer & Earn — Mashreq NEO',
        'description': 'Refer up to 5 friends to Mashreq NEO in 90 days — earn AED 100–200 per successful referral.',
        'external_url': 'https://www.mashreq.com/uae/neo/refer-and-earn/refer-accounts/',
    },
    {
        'place_slug': 'adcb-hayyak',
        'discount_slug': 'adcb-hayyak-referral',
        'title': 'Refer & Earn — ADCB Hayyak',
        'description': 'Refer a friend to ADCB — when they open an eligible account, you both get a cash reward.',
        'external_url': 'https://www.adcb.com/en/personal/promotions/refer-a-friend',
    },
    {
        'place_slug': 'etisalat-by-e-and',
        'discount_slug': 'etisalat-by-e-and-referral',
        'title': 'Refer & Earn — Etisalat by e&',
        'description': 'Invite a friend to e& — get 500MB of free mobile data per successful invite.',
        'external_url': 'https://www.etisalat.ae/en/c/invite-a-friend.html',
    },
    {
        'place_slug': 'du-pay',
        'discount_slug': 'du-pay-referral',
        'title': 'Refer & Earn — du Pay',
        'description': 'Invite friends to du Pay — they enter your code at sign-up via the "Got a referral code?" screen, and both of you earn rewards once they complete their first qualifying transaction.',
        'external_url': 'https://dupay.ae/en/help/articles/invite-and-earn',
    },
]


def seed(apps, schema_editor):
    Program = apps.get_model("discounts", "Program")
    Place = apps.get_model("places", "Place")
    Discount = apps.get_model("discounts", "Discount")

    Program.objects.update_or_create(
        slug=PROGRAM["slug"],
        defaults={k: v for k, v in PROGRAM.items() if k != "slug"},
    )

    place_by_slug = {}
    for spec in PLACES:
        place, _ = Place.objects.update_or_create(
            slug=spec["slug"],
            defaults={
                "name": spec["name"],
                "category": spec["category"],
                "area": spec["area"],
                "website": spec.get("website", ""),
                "is_published": True,
            },
        )
        place_by_slug[spec["slug"]] = place

    for d in DISCOUNTS:
        place = place_by_slug.get(d["place_slug"])
        if place is None:
            continue
        Discount.objects.update_or_create(
            slug=d["discount_slug"],
            defaults={
                "place": place,
                "title": d["title"][:200],
                "discount_type": "referral",
                "source_program": "referral",
                "description": d["description"],
                "external_url": d["external_url"],
                "is_active": True,
                "is_featured": False,
            },
        )


def reverse(apps, schema_editor):
    Program = apps.get_model("discounts", "Program")
    Place = apps.get_model("places", "Place")
    Discount = apps.get_model("discounts", "Discount")
    Discount.objects.filter(slug__in=[d["discount_slug"] for d in DISCOUNTS]).delete()
    Place.objects.filter(slug__in=[p["slug"] for p in PLACES]).delete()
    Program.objects.filter(slug=PROGRAM["slug"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0032_remove_broken_referral_programs"),
        ("places", "0006_alter_place_area_alter_place_category"),
    ]

    operations = [
        migrations.RunPython(seed, reverse),
    ]
