# Generated by Django 6.0.5 on 2026-05-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0033_seed_referrals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='source_program',
            field=models.CharField(blank=True, choices=[('in_house', 'Loyalty program'), ('fazaa', 'Fazaa'), ('esaad', 'Esaad'), ('entertainer', 'Entertainer'), ('zomato', 'Zomato Pro / Gold'), ('repeat', 'Repeat'), ('playbook', 'Playbook'), ('elite_club', 'Elite Club'), ('supper_club', 'Supper Club ME'), ('emirates_platinum', 'Emirates Platinum'), ('shukran', 'Shukran'), ('share_rewards', 'SHARE Rewards'), ('emirates_skywards', 'Emirates Skywards'), ('atlantis_circle', 'Atlantis Circle'), ('u_by_emaar', 'U By Emaar'), ('al_futtaim_blue', 'Blue (Al-Futtaim)'), ('adcb_touchpoints', 'ADCB TouchPoints'), ('referral', 'Refer & Earn')], default='', help_text='Which program/card offers this discount. Leave blank if none.', max_length=20),
        ),
    ]
