# Generated by Django 6.0.5 on 2026-05-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('restaurant', 'Restaurants & Cafes'), ('attraction', 'Attractions & Entertainment'), ('hotel', 'Hotels & Staycations'), ('retail', 'Retail, Beauty & Services')], max_length=20)),
                ('area', models.CharField(help_text='e.g. Dubai Marina, Downtown, JBR', max_length=120)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category'], name='places_plac_categor_0dcb38_idx'), models.Index(fields=['area'], name='places_plac_area_c03e2e_idx'), models.Index(fields=['is_published'], name='places_plac_is_publ_9d19fd_idx')],
            },
        ),
    ]
