# Generated by Django 6.0.5 on 2026-05-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_members_only',
            field=models.BooleanField(default=False, help_text='Hidden from anonymous visitors; visible to signed-in users.'),
        ),
    ]
