# Generated by Django 6.0.5 on 2026-05-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_is_members_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=60)),
                ('sort_order', models.PositiveSmallIntegerField(default=100, help_text='Lower = higher in the filter panel.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='place',
            name='experiences',
            field=models.ManyToManyField(blank=True, help_text='What kind of visit this place supports — used as a home-page filter.', related_name='places', to='places.experience'),
        ),
    ]
