# Generated by Django 6.0.5 on 2026-05-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_seed_experiences_and_autotag'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['lat', 'lng'], name='places_plac_lat_3d68aa_idx'),
        ),
    ]
