# Generated by Django 6.0.5 on 2026-05-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_place_lat_place_lng_place_places_plac_lat_3d68aa_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='area',
            field=models.CharField(blank=True, help_text='e.g. Dubai Marina, Downtown, JBR. Leave blank for online/UAE-wide services.', max_length=120),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('restaurant', 'Restaurants & Cafes'), ('attraction', 'Attractions & Entertainment'), ('hotel', 'Hotels & Staycations'), ('retail', 'Retail, Beauty & Services'), ('service', 'Online & At-Home Services')], max_length=20),
        ),
    ]
