# Generated by Django 6.0.5 on 2026-05-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_place_area_alter_place_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='aggregates_branches',
            field=models.BooleanField(default=False, help_text="When True, this Place's detail page rolls up Discount rows from sibling Places whose name starts with this Place's name. Used for brand-level Places (e.g. 'Jones the Grocer') that share branding with multiple branch Places."),
        ),
    ]
