# Generated by Django 6.0.5 on 2026-05-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_ingest_entertainer_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='logo_url_override',
            field=models.CharField(blank=True, help_text='Direct image URL for the brand logo (e.g. an Entertainer CDN URL). Takes precedence over the domain-derived icon.horse URL when set.', max_length=500),
        ),
    ]
